#!/bin/sh

xz=`which xz`
bz=`which bzip2`
gz=`which gzip`

preferred=$xz
params="-ev"
extension="xz"

if [ "" = "$preferred" ] ; then
preferred=$bz
params="-v9"
extension="bz2"
fi

if [ "" = "$preferred" ] ; then
preferred=$gz
params="-v9"
extension="gz"
fi

if [ "" = "$preferred" ] ; then
echo "Proper archiver not found"
exit
fi


if [ "" = "$1" ] ; then
echo "Usage: tarit directory"
exit
fi

unslashed=$1
slashed=`echo $1 | grep "/"`

if [ "" != "$slashed" ] ; then
unslashed=`echo $1 | sed 's/\/$//'`
echo "Directory names must not contain trailing slashes. So we are going to strip it."
echo "Result: $slashed => $unslashed"
fi

echo "Selected archiver: $preferred (Params: $params)"

if [ -d $unslashed ] ; then
	packed="${unslashed}.tar.$extension"
	echo "Archive: ${unslashed}.tar (Directory ${unslashed})"
	echo "Compress: $preferred $params ${unslashed}.tar"

	if [ -f $packed ] ; then
		echo "Compressed destination, $packed, already exists. Aborting."
		exit
	fi

	echo "Calculating size of directory"
	dirsize=`du -h $unslashed | tail -1 | awk '{printf \$1}'`
	echo "Directory size: $dirsize"

	echo "Creating tar archive"
	tar cf $unslashed.tar $unslashed
	$preferred $params $unslashed.tar

	if [ -f $packed ] ; then
		echo "Compressed archive, $packed, seems to be created. Finalize by removal!"
		rm -rf $unslashed
		echo "Done."
	fi

else
	echo "Can not archive unexistent archives"
fi
