#!/bin/sh

xz=`which xz`
bz=`which bzip2`
gz=`which gzip`

preferred=$xz
params="-ev"
extension="xz"

if [ "" = "$preferred" ] ; then
preferred=$bz
params="-v9"
extension="bz2"
fi

if [ "" = "$preferred" ] ; then
preferred=$gz
params="-v9"
extension="gz"
fi

urar="x"
xuzip="-d ."
utgz="zvxf"
utxz="Jvxf"
ubz2="jvxf"
ubz="jvxf"
utar="--list --file"
packonly="0"

if [ "" = "$preferred" ] ; then
	echo "Proper archiver not found"
	exit
fi


if [ "" = "$1" ] ; then
	echo "Usage: tarit directory"
	exit
fi

unslashed=$1
slashed=`echo $1 | grep "/"`

if [ "" != "$slashed" ] ; then
	unslashed=`echo $1 | sed 's/\/$//'`
	echo "Directory names must not contain trailing slashes. So we are going to strip it."
	echo "Result: $slashed => $unslashed"
fi

echo "Selected archiver: $preferred (Params: $params)"

if [ -d $unslashed ] ; then
	packed="${unslashed}.tar.$extension"
	echo "Archive: ${unslashed}.tar (Directory ${unslashed})"
	echo "Compress: $preferred $params ${unslashed}.tar"

	if [ -f $packed ] ; then
		echo "Compressed destination, $packed, already exists. Aborting."
		exit
	fi

	echo "Calculating size of directory"
	dirsize=`du -h $unslashed | tail -1 | awk '{printf \$1}'`
	echo "Directory size: $dirsize"

	echo "Creating tar archive"
	tar cf $unslashed.tar $unslashed
	if [ "$?" != "0" ] ; then
		echo "Something failed during the tar session. I will not continue."
		exit
	fi
	$preferred $params $unslashed.tar
	if [ -f $packed ] ; then
		echo "Compressed archive, $packed, seems to be created. Finalize by removal!"
		rm -rf $unslashed
		echo "Done."
	fi
else
	if [ -f $unslashed ] ; then
		allowedExtensions="zip:unzip rar:rar tgz:tar tar:tar txz:tar tbz:tar tbz2:tar"
		fileArchive=""
		filePacker=""
		extractCmd=""
		hasAllowed="0"
		currentExtension=""
		for ext in $allowedExtensions
		do
			testExtension=`echo $ext | cut -d ':' -f1`
			testPacker=`echo $ext | cut -d ':' -f2`
			allowedFile=`echo $unslashed | grep "$testExtension\$"`
			if [ "$allowedFile" != "" ] ; then
				hasAllowed="1"
				eval "extractCmd=\$u$testExtension"
				if [ "$extractCmd" = "" ] ; then
					echo "No prepared extractor found for $testExtension"
					exit
				fi
				currentExtension=$testExtension
				filePacker=`which $testPacker`
				echo "$unslashed format is $testExtension, archiver set to $filePacker"
			fi
		done
		if [ "$hasAllowed" = "0" ] ; then
			echo "This is a file is unsupported"
			exit
		fi
		if [ "$filePacker" != "" ] && [ -f $filePacker ] && [ "$currentExtension" != "" ] ; then
			unExtend=`echo $unslashed | sed "s/\.$currentExtension$//g"`
			tarArchive="$unExtend.tar";
			tarFolder="$tarArchive.\$tmp\$"
			echo "RePack $unExtend(.$currentExtension) => $tarArchive ($tarFolder)"
			if [ "$tarFolder" != "" ] && [ -d $tarFolder ] ; then
				echo "Clean up."
				rm -rfv $tarFolder
			fi
			if [ ! -d $tarFolder ] && [ ! -f $tarArchive ] && [ ! -f $tarArchive.$extension ] ; then
				echo "Creating $tarFolder"
				mkdir $tarFolder
				# Make sure it actually worked
				if [ -d $tarFolder] ; then
					cd $tarFolder
					doExtract="$filePacker $extractCmd ../$unExtend.$currentExtension"
					echo $doExtract
					$doExtract
					if [ "$?" != "0" ] ; then
						echo "The extracting archiver gave me an errorcode ($?) that made me stop the process"
						exit
					fi
					echo "Calculating size of directory"
					dirsize=`du -h . | tail -1 | awk '{printf \$1}'`
					echo "Directory size: $dirsize - beginning the tar session"
					tar cf ../$tarArchive .
					if [ "$?" != "0" ] ; then
						echo "The tar archiving process failed to succeed. Packing process aborted."
						exit
					fi
					cd ..
					echo "Compress: $preferred $params $tarArchive"
					if [ -f $tarArchive ] && [ ! -f $tarArchive.$extension ] ; then
						rm -rf $tarFolder
						$preferred $params $tarArchive
						echo "Comparision:"
						ls -l $unExtend.*
						echo "Cleaning up"
						rm -v $unExtend.$currentExtension
					fi
				fi
			else
				echo "$tarArchive (or the packed one) already exists in this folder."
				echo "As it may be another archive than the one you would like to create, I have bailed out."
				if [ -f $tarArchive ] && [ ! -f $tarArchive.$extension ]; then
					echo "I will however pack this one for you, since there are no archived file present"
					echo $preferred $params $tarArchive
					$preferred $params $tarArchive
				fi
			fi
		else
			echo "This is a file is unsupported"
		fi
	fi
fi
